require: rubocop-rspec

inherit_gem:
  rubocop-fjord:
    - 'config/rubocop.yml'
    - 'config/rails.yml'

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*

RSpec/ContextWording:
  AllowedPatterns:
    - 場合$

RSpec/NestedGroups:
  Max: 4
